### PR TITLE
Dwf sparse pca

### PR DESCRIPTION
**Pull request by vene**
I hope this is what you mean. It runs fast now on my system.

Also I fixed some pep8.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Could you please do that only on win32? It will conflict will the way Debian packages joblib outside of the scikit.

**Comment by vene** [comment]
like this? or wrap the whole block including the imports?

**Comment by GaelVaroquaux** [comment]
Actually the whole thing (including imports) needs to be protected to work on Debian.

**Comment by vene** [comment]
Done (writing this so you get notified)

**Pull request merged**
