### PR TITLE
Correct hungarian support for rectangular matrices

### PR DESCRIPTION
**Pull request by WeatherGod**
Additional testing revealed that my previous square2rect branch was wrong in the case of m > n.  Therefore, this branch fixes that mistake by going the route of padding the array and recording the original matrix shape.

Also modified the hungarian test to also test the transpose of the test arrays to see if identical results occur.

As a consequence of this new approach, we do not need some of the code that was introduced by the zerohungarian branch (but we do still need to keep some of it).

### CODE REVIEW

**Comment by WeatherGod** [comment]
Heh, oddly enough... my tracking results are better with the code from zerohungarian branch.  Weird...

**Comment by GaelVaroquaux** [comment]
Hey,

Sorry, that pull request had slipped under my radar. I was about to merge it, but I noticed you last remark, and I am not sure what to do about it.  Could you comment a bit more on it: I don't see how supporting non square matrix should affect the performance of a hungarian algorithm. But maybe I understood you wrong.

**Comment by WeatherGod** [comment]
No, it is not a performance issue.  I am not 100% sure that the results are correct.  I will be doing further analysis today.

**Comment by GaelVaroquaux** [comment]
> No, it is not a performance issue. 

OK, so you are saying that the square matrices are taking a performance
hit because of the support for non-square matrices. That's supprising, it
would seem to me that non-square matrices can simply be extend to square
matrices, and thus that square matrix code shouldn't be changed (as you
can see, I haven't reviewed your code well, and right now I am at a
conference and I can do it).

> I am not 100% sure that the results are correct.  I will be doing further analysis today.

Tahnks, keep me poster.

**Comment by WeatherGod** [comment]
> OK, so you are saying that the square matrices are taking a performance hit because of the support for non-square matrices. That's supprising, it would seem to me that non-square matrices can simply be extend to square matrices, and thus that square matrix code shouldn't be changed (as you can see, I haven't reviewed your code well, and right now I am at a conference and I can do it).

No... I am not talking at all about performance (in terms of speed or memory usage).  I am only talking about the _correctness_ of the algorithm output.  I need to find some more test cases to see how the algorithm is right or wrong.

**Comment by WeatherGod** [comment]
Ok, I finally figured it out. It was a combination of issues. First, we don't _need_ to pad the cost matrix.  One could also transpose it when m > n and then just make sure to switch the columns of the results before returning it.

Second (and most importantly!), the functional method "hungarian()" strips out important information when the matrix is rectangular. When the input cost matrix is square, we know that there will be an association for each row.  However, when m > n, there can only be n associations, which means some rows are not accounted for in the results list from H.compute().  Because hungarian() strips the first column from the results list, we typically loop over the enumeration of results, accidentally assuming that the results are for the first n rows.

Therefore, I recommend not stripping the first column from the results list in hungarian().  Also, if desired, I can make a new pull request that implements the rectangular hungarian solver without cost padding.

**Comment by GaelVaroquaux** [comment]
> Ok, I finally figured it out. It was a combination of issues. First, we don't _need_ to pad the cost matrix.

OK, that's good to know.

> One could also transpose it when m > n and then just make sure to switch the columns of the results before returning it.

Yes, that seems the right thing to do.

> Therefore, I recommend not stripping the first column from the results list in hungarian().

Fair enough. Could you just make sure that find_permutation still works.

> Also, if desired, I can make a new pull request that implements the rectangular hungarian solver without cost padding.

That would be great. Thanks

**Pull request closed without merging**
