### PR TITLE
Quick rect

### PR DESCRIPTION
**Pull request by WeatherGod**
A redone and improved rectangular hungarian solver.  Includes fixes to the tests and change to the return value of the hungarian() method.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Looks great. I gather that the tests still pass (haven't had time to check).

Could you update the docstrings please.

**Comment by WeatherGod** [comment]
I did some doc fixes, but I am unclear about what the docs for hungarian() and find_permutation() were talking about. Therefore, I left them alone for right now. Perhaps you could make it clearer what was your intent for those docs?

**Comment by WeatherGod** [comment]
Didn't mean to close this request. I am updating this branch to work with the changed namespace (any module within utils aren't found through the old name, I think).

**Comment by GaelVaroquaux** [comment]
Cool, thanks a lot. I'll merge it after that. I didn't merge it earlier because I wasn't sure that it was right :)

**Comment by WeatherGod** [comment]
Hmm, looks like I have to do a new pull request.  I think my rebase to your hungarian branch caused this pull request to lose track of my quickRect branch.

**Comment by GaelVaroquaux** [comment]
> Hmm, looks like I have to do a new pull request.  I think my rebase to your hungarian branch caused this pull request to lose track of my quickRect branch.

Yes, it does happen with github. Doing a new pull request is the right
solution.

**Pull request merged**
